version: '3.0'
volumes: 
    
services: 
    api:
        build:
            dockerfile: Dockerfile.multi
            context: .
        ports: 
            - '8080:8080'
        volumes: 
            - ./logs:/app/logs